server:
  port: 8888
spring:
  application:
    name: Config-Center

    cloud:
      config:
        server:
          git:
            uri: https://github.com/Mayday4671/Mayday.git
          default-lable: master
